/*
Wisp API

Wisp API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobGetRequest{}

// JobGetRequest Job get request serializer.
type JobGetRequest struct {
	Id string `json:"id"`
}

type _JobGetRequest JobGetRequest

// NewJobGetRequest instantiates a new JobGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobGetRequest(id string) *JobGetRequest {
	this := JobGetRequest{}
	this.Id = id
	return &this
}

// NewJobGetRequestWithDefaults instantiates a new JobGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobGetRequestWithDefaults() *JobGetRequest {
	this := JobGetRequest{}
	return &this
}

// GetId returns the Id field value
func (o *JobGetRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobGetRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobGetRequest) SetId(v string) {
	o.Id = v
}

func (o JobGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *JobGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobGetRequest := _JobGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobGetRequest)

	if err != nil {
		return err
	}

	*o = JobGetRequest(varJobGetRequest)

	return err
}

type NullableJobGetRequest struct {
	value *JobGetRequest
	isSet bool
}

func (v NullableJobGetRequest) Get() *JobGetRequest {
	return v.value
}

func (v *NullableJobGetRequest) Set(val *JobGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobGetRequest(val *JobGetRequest) *NullableJobGetRequest {
	return &NullableJobGetRequest{value: val, isSet: true}
}

func (v NullableJobGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


