/*
Wisp API

Wisp API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wisp

import (
	"encoding/json"
)

// JobPostRequest Job post request serializer.
type JobPostRequest struct {
	Choice ClusterOffer `json:"choice"`
	Config ConstrainRequest `json:"config"`
	Project Project `json:"project"`
}

// NewJobPostRequest instantiates a new JobPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobPostRequest(choice ClusterOffer, config ConstrainRequest, project Project) *JobPostRequest {
	this := JobPostRequest{}
	this.Choice = choice
	this.Config = config
	this.Project = project
	return &this
}

// NewJobPostRequestWithDefaults instantiates a new JobPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobPostRequestWithDefaults() *JobPostRequest {
	this := JobPostRequest{}
	return &this
}

// GetChoice returns the Choice field value
func (o *JobPostRequest) GetChoice() ClusterOffer {
	if o == nil {
		var ret ClusterOffer
		return ret
	}

	return o.Choice
}

// GetChoiceOk returns a tuple with the Choice field value
// and a boolean to check if the value has been set.
func (o *JobPostRequest) GetChoiceOk() (*ClusterOffer, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Choice, true
}

// SetChoice sets field value
func (o *JobPostRequest) SetChoice(v ClusterOffer) {
	o.Choice = v
}

// GetConfig returns the Config field value
func (o *JobPostRequest) GetConfig() ConstrainRequest {
	if o == nil {
		var ret ConstrainRequest
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *JobPostRequest) GetConfigOk() (*ConstrainRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *JobPostRequest) SetConfig(v ConstrainRequest) {
	o.Config = v
}

// GetProject returns the Project field value
// If the value is explicit nil, the zero value for Project will be returned
func (o *JobPostRequest) GetProject() Project {
	if o == nil {
		var ret Project
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobPostRequest) GetProjectOk() (*Project, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *JobPostRequest) SetProject(v Project) {
	o.Project = v
}

func (o JobPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["choice"] = o.Choice
	}
	if true {
		toSerialize["config"] = o.Config
	}

	toSerialize["project"] = o.Project
	
	return json.Marshal(toSerialize)
}

type NullableJobPostRequest struct {
	value *JobPostRequest
	isSet bool
}

func (v NullableJobPostRequest) Get() *JobPostRequest {
	return v.value
}

func (v *NullableJobPostRequest) Set(val *JobPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobPostRequest(val *JobPostRequest) *NullableJobPostRequest {
	return &NullableJobPostRequest{value: val, isSet: true}
}

func (v NullableJobPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


