/*
Wisp API

Wisp API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wisp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterListResponse{}

// ClusterListResponse Cluster list response serializer.
type ClusterListResponse struct {
	Clusters []Cluster `json:"clusters"`
}

type _ClusterListResponse ClusterListResponse

// NewClusterListResponse instantiates a new ClusterListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterListResponse(clusters []Cluster) *ClusterListResponse {
	this := ClusterListResponse{}
	this.Clusters = clusters
	return &this
}

// NewClusterListResponseWithDefaults instantiates a new ClusterListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterListResponseWithDefaults() *ClusterListResponse {
	this := ClusterListResponse{}
	return &this
}

// GetClusters returns the Clusters field value
func (o *ClusterListResponse) GetClusters() []Cluster {
	if o == nil {
		var ret []Cluster
		return ret
	}

	return o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value
// and a boolean to check if the value has been set.
func (o *ClusterListResponse) GetClustersOk() ([]Cluster, bool) {
	if o == nil {
		return nil, false
	}
	return o.Clusters, true
}

// SetClusters sets field value
func (o *ClusterListResponse) SetClusters(v []Cluster) {
	o.Clusters = v
}

func (o ClusterListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clusters"] = o.Clusters
	return toSerialize, nil
}

func (o *ClusterListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clusters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterListResponse := _ClusterListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterListResponse)

	if err != nil {
		return err
	}

	*o = ClusterListResponse(varClusterListResponse)

	return err
}

type NullableClusterListResponse struct {
	value *ClusterListResponse
	isSet bool
}

func (v NullableClusterListResponse) Get() *ClusterListResponse {
	return v.value
}

func (v *NullableClusterListResponse) Set(val *ClusterListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterListResponse(val *ClusterListResponse) *NullableClusterListResponse {
	return &NullableClusterListResponse{value: val, isSet: true}
}

func (v NullableClusterListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


