/*
Wisp API

Wisp API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectYaml type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectYaml{}

// ProjectYaml Project configuration serializer.
type ProjectYaml struct {
	Type NullableString `json:"type"`
	ProjectId NullableString `json:"project_id"`
	Name NullableString `json:"name"`
	Env map[string]string `json:"env"`
}

type _ProjectYaml ProjectYaml

// NewProjectYaml instantiates a new ProjectYaml object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectYaml(type_ NullableString, projectId NullableString, name NullableString, env map[string]string) *ProjectYaml {
	this := ProjectYaml{}
	this.Type = type_
	this.ProjectId = projectId
	this.Name = name
	this.Env = env
	return &this
}

// NewProjectYamlWithDefaults instantiates a new ProjectYaml object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectYamlWithDefaults() *ProjectYaml {
	this := ProjectYaml{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProjectYaml) GetType() string {
	if o == nil || o.Type.Get() == nil {
		var ret string
		return ret
	}

	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectYaml) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// SetType sets field value
func (o *ProjectYaml) SetType(v string) {
	o.Type.Set(&v)
}

// GetProjectId returns the ProjectId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProjectYaml) GetProjectId() string {
	if o == nil || o.ProjectId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectYaml) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// SetProjectId sets field value
func (o *ProjectYaml) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProjectYaml) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectYaml) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *ProjectYaml) SetName(v string) {
	o.Name.Set(&v)
}

// GetEnv returns the Env field value
// If the value is explicit nil, the zero value for map[string]string will be returned
func (o *ProjectYaml) GetEnv() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectYaml) GetEnvOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *ProjectYaml) SetEnv(v map[string]string) {
	o.Env = v
}

func (o ProjectYaml) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectYaml) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type.Get()
	toSerialize["project_id"] = o.ProjectId.Get()
	toSerialize["name"] = o.Name.Get()
	if o.Env != nil {
		toSerialize["env"] = o.Env
	}
	return toSerialize, nil
}

func (o *ProjectYaml) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"project_id",
		"name",
		"env",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectYaml := _ProjectYaml{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectYaml)

	if err != nil {
		return err
	}

	*o = ProjectYaml(varProjectYaml)

	return err
}

type NullableProjectYaml struct {
	value *ProjectYaml
	isSet bool
}

func (v NullableProjectYaml) Get() *ProjectYaml {
	return v.value
}

func (v *NullableProjectYaml) Set(val *ProjectYaml) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectYaml) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectYaml) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectYaml(val *ProjectYaml) *NullableProjectYaml {
	return &NullableProjectYaml{value: val, isSet: true}
}

func (v NullableProjectYaml) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectYaml) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


