/*
Wisp API

Wisp API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wisp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterActionResponse{}

// ClusterActionResponse Cluster action response serializer.
type ClusterActionResponse struct {
	ClusterName string `json:"cluster_name"`
	Status string `json:"status"`
	Message string `json:"message"`
}

type _ClusterActionResponse ClusterActionResponse

// NewClusterActionResponse instantiates a new ClusterActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterActionResponse(clusterName string, status string, message string) *ClusterActionResponse {
	this := ClusterActionResponse{}
	this.ClusterName = clusterName
	this.Status = status
	this.Message = message
	return &this
}

// NewClusterActionResponseWithDefaults instantiates a new ClusterActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterActionResponseWithDefaults() *ClusterActionResponse {
	this := ClusterActionResponse{}
	return &this
}

// GetClusterName returns the ClusterName field value
func (o *ClusterActionResponse) GetClusterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value
// and a boolean to check if the value has been set.
func (o *ClusterActionResponse) GetClusterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterName, true
}

// SetClusterName sets field value
func (o *ClusterActionResponse) SetClusterName(v string) {
	o.ClusterName = v
}

// GetStatus returns the Status field value
func (o *ClusterActionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClusterActionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClusterActionResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *ClusterActionResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ClusterActionResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ClusterActionResponse) SetMessage(v string) {
	o.Message = v
}

func (o ClusterActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster_name"] = o.ClusterName
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ClusterActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cluster_name",
		"status",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterActionResponse := _ClusterActionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterActionResponse)

	if err != nil {
		return err
	}

	*o = ClusterActionResponse(varClusterActionResponse)

	return err
}

type NullableClusterActionResponse struct {
	value *ClusterActionResponse
	isSet bool
}

func (v NullableClusterActionResponse) Get() *ClusterActionResponse {
	return v.value
}

func (v *NullableClusterActionResponse) Set(val *ClusterActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterActionResponse(val *ClusterActionResponse) *NullableClusterActionResponse {
	return &NullableClusterActionResponse{value: val, isSet: true}
}

func (v NullableClusterActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


