/*
Wisp API

Wisp API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wisp

import (
	"encoding/json"
)

// UserPublicKeyResponse struct for UserPublicKeyResponse
type UserPublicKeyResponse struct {
	PublicKey string `json:"public_key"`
}

// NewUserPublicKeyResponse instantiates a new UserPublicKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPublicKeyResponse(publicKey string) *UserPublicKeyResponse {
	this := UserPublicKeyResponse{}
	this.PublicKey = publicKey
	return &this
}

// NewUserPublicKeyResponseWithDefaults instantiates a new UserPublicKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPublicKeyResponseWithDefaults() *UserPublicKeyResponse {
	this := UserPublicKeyResponse{}
	return &this
}

// GetPublicKey returns the PublicKey field value
func (o *UserPublicKeyResponse) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *UserPublicKeyResponse) GetPublicKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *UserPublicKeyResponse) SetPublicKey(v string) {
	o.PublicKey = v
}

func (o UserPublicKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["public_key"] = o.PublicKey
	}
	return json.Marshal(toSerialize)
}

type NullableUserPublicKeyResponse struct {
	value *UserPublicKeyResponse
	isSet bool
}

func (v NullableUserPublicKeyResponse) Get() *UserPublicKeyResponse {
	return v.value
}

func (v *NullableUserPublicKeyResponse) Set(val *UserPublicKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPublicKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPublicKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPublicKeyResponse(val *UserPublicKeyResponse) *NullableUserPublicKeyResponse {
	return &NullableUserPublicKeyResponse{value: val, isSet: true}
}

func (v NullableUserPublicKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPublicKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


